<!DOCTYPE html>
<html>
<head>
	<title>Test Armada</title>
	<link rel="stylesheet" type="text/css" href="/css/normalize.css">
	<link rel="stylesheet" type="text/css" href="/css/common.css">
	<link rel="stylesheet" type="text/css" href="/css/header.css">
	<link rel="stylesheet" type="text/css" href="/css/home.css">
	<link rel="stylesheet" type="text/css" href="/css/doc.css">
	<link rel="stylesheet" type="text/css" href="/css/training.css">
	<link rel="stylesheet" type="text/css" href="/css/faq.css">
	<link rel="stylesheet" type="text/css" href="/css/contact.css">
	<link rel="stylesheet" type="text/css" href="/css/search.css">
	<link rel="stylesheet" type="text/css" href="/css/custom.css">
	<link rel="stylesheet" type="text/css" href="/css/slick.css">
	<link rel="stylesheet" type="text/css" href="/css/prism.css">
	<link rel="stylesheet" type="text/css" href="/css/responsive.css">
	
	<link rel="shortcut icon" href="/documentation/images/favicon.ico">
	
</head>
<body>
	
	<header>
		<a href="/">
			<img src="/documentation/images/ta-logo.png" class="logo" alt="Main Brand Logo"
				 srcset="/documentation/images/ta-logo%402x.png 2x, /documentation/images/ta-logo%403x.png 3x">
		</a>
		<form action="/search" method="get">
			<input type="text" id="search-box" name="query" placeholder="Search" class="search-box">
			<div class="select-box">
				<select name="fleet" id="fleet-box" onchange="document.getElementById('search-box').focus();">
					<option value="all">All Fleets</option>
					
					<option value="Functional Testing">Functional Testing</option>
					
					<option value="Mocking">Mocking</option>
					
					<option value="Performance Testing">Performance Testing</option>
					
					<option value="Data Insights">Data Insights</option>
					
				</select>
			</div>
		</form>
		<div class="nav-links">
			
			<div class="nav-links__fleets">
				<a class="nav-links__fleets-btn">
					Fleets <img src="/images/arrow-down-icon.png" class="arrow-down-icon"
								srcset="/images/arrow-down-icon%402x.png 2x,
										/images/arrow-down-icon%403x.png 3x">
				</a>
				<div class="nav-links__fleets-content">
					<a href="/">
						All Fleets
					</a>
					
					<a href="/Functional Testing/">
						Functional Testing
					</a>
					
					<a href="/Mocking/">
						Mocking
					</a>
					
					<a href="/Performance Testing/">
						Performance Testing
					</a>
					
					<a href="/Data Insights/">
						Data Insights
					</a>
					
				</div>
			</div>
			
			
			
			
			<a href="/documentation/About.html" class="nav-links__main-links">About Us</a>
			
			
			
			
			
			
			<a href="/faq" class="nav-links__main-links">FAQ</a>
			
			
			
			<a href="https://github.com/TestArmada/" target="_blank" class="nav-links__main-links">GitHub</a>
			
		</div>
	</header>

	<div class="container">
		  <div class="clear"></div>
<div class="doc-container">
  <div class="breadcrumb doc-breadcrumb">
    <p>
      <a class="breadcrumb__link" href="/">Home</a>
      <img src="/images/arrow-right-icon.png"
           srcset="/images/arrow-right-icon%402x.png 2x,
                   /images/arrow-right-icon%403x.png 3x"
           class="arrow-right-icon">
      <a class="breadcrumb__link" href="/Functional Testing/">Functional Testing</a>
      <img src="/images/arrow-right-icon.png"
           srcset="/images/arrow-right-icon%402x.png 2x,
                   /images/arrow-right-icon%403x.png 3x"
           class="arrow-right-icon">
      <a class="breadcrumb__link" href="/documentation/Functional Testing/Native Android/JAVA/Introduction">Native Android JAVA</a>
      <img src="/images/arrow-right-icon.png"
           srcset="/images/arrow-right-icon%402x.png 2x,
                   /images/arrow-right-icon%403x.png 3x"
           class="arrow-right-icon">
      <a class="breadcrumb__link" href="/Functional Testing/Native Android/JAVA/Training Guide">Training Guide</a>
      <img src="/images/arrow-right-icon.png"
           srcset="/images/arrow-right-icon%402x.png 2x,
                   /images/arrow-right-icon%403x.png 3x"
           class="arrow-right-icon">
      <span class="breadcrumb__current-page">Training 201</span>
    </p>
  </div>
  <div class="clear"></div>
  <div class="training-container">
    <div class="sidebar">
<div class="training-doc-link">
<div class="training-doc-link-left">
<img class="training-doc-link-left__img" src="/images/training/checked.png" srcset="/images/training/checked%402x.png 2x, /images/training/checked%403x.png 3x" /><hr class="training-doc-link-left__hr training-doc-link-left__hr-completed" /></div>
<p class="training-doc-link__text">
<a class="training-doc-link__text-completed" href="./Introduction">Introduction</a></p>
</div>
<div class="training-doc-link">
<div class="training-doc-link-left">
<img class="training-doc-link-left__img" src="/images/training/checked.png" srcset="/images/training/checked%402x.png 2x, /images/training/checked%403x.png 3x" /><hr class="training-doc-link-left__hr training-doc-link-left__hr-completed" /></div>
<p class="training-doc-link__text">
<a class="training-doc-link__text-completed" href="./Setup a looper job">Setup a looper job</a></p>
</div>
<div class="training-doc-link">
<div class="training-doc-link-left">
<img class="training-doc-link-left__img" src="/images/training/actived.png" srcset="/images/training/actived%402x.png 2x, /images/training/actived%403x.png 3x" /><hr class="training-doc-link-left__hr training-doc-link-left__hr-pending" /></div>
<p class="training-doc-link__text">
<a class="training-doc-link__text-current" href="./Config .looper.yml">Config .looper.yml</a></p>
</div>
<div class="training-doc-link">
<div class="training-doc-link-left">
<img class="training-doc-link-left__img" src="/images/training/unread.png" srcset="/images/training/unread%402x.png 2x, /images/training/unread%403x.png 3x" /></div>
<p class="training-doc-link__text">
<a class="training-doc-link__text-pending" href="./Build the looper job">Build the looper job</a></p>
</div>
</div>
<div class="training-doc-nav-btn">
<a href="./Setup a looper job"><img src="/images/training/btn-left.png" srcset="/images/training/btn-left%402x.png 2x, /images/training/btn-left%403x.png 3x" /></a>
</div>
<div class="training-content markdown">
<h3>Config <code>.looper.yml</code> in your project</h3>
<p>First let's see how a minimum full config looks like:</p>
<pre><code class="language-yaml">    inherit: 'job://otto-Android_native'

    tools:
        android:
            - tools
            - platform-tools
            - android-25
            - build-tools;25.0.1
            - extras;android;m2repository
        gradle: 4.2.1

    envs:
        global:
            variables:
                APK_PATH: ${YOUR_APK_PATH}
                TEST_APK_PATH: ${YOUR_TEST_APK_PATH}
                PACKAGE: ''
                #ADMIRAL_PROJECT: Boilerplate Android
                #FAIL_JOB_ON_TEST_FAIL: false

    flows:
        default:
            - if not prepare apks, build them here, make sure they are under ${YOUR_APK_PATH} and ${YOUR_TEST_APK_PATH}
            - shell (name run_tests): |
                curl --header &quot;Authorization: token ${GH_API_TOKEN}&quot; \
                --header &quot;Accept: application/vnd.github.v3.raw&quot; \
                --location https://gecgithub01.walmart.com/api/v3/repos/otto/scripts/contents/looper/flank/flank.sh?ref=${BUILD_URL_REF} \
                | bash
</code></pre>
<ol>
<li><p>First, it's recommended that add <code>inherit: 'job://otto-Android_native'</code> at the first line of your <code>.looper.yml</code> it will handle all default envs for you if you missed some essential envs.</p></li>
<li><p>Next add Android and Gradle tool stack in looper as described for <a href="http://looper.walmart.com/docs/tools/android.html">Android tool</a> and <a href="http://looper.walmart.com/docs/tools/gradle.html">Gradle tool</a>.</p></li>
<li><p>Setup essential <code>envs</code>, reference by the <a href="../../API%20Guide.md#Environment%20variables">env list</a>, <code>APK_PATH</code> and <code>TEST_APK_PATH</code> is the two you must provided, <code>FAIL_JOB_ON_TEST_FAIL</code> is used when results chart plugin is installed in the looper job, and it needs the build at least passed once.</p>
<p>If setup env <code>ADMIRAL_PROJECT</code>, e.g. <code>Boilerplate Android</code>, TDK will report to admiral2 dashboard after tests done, and you can check at http://admiral2.walmart.com/.</p></li>
<li><p>Call looper flows</p>
<ol>
<li>Build your apk and test apk under the path same under <code>env</code> variables</li>
<li>Call TDK scripts as it is, recommend define your own <code>GH_API_TOKEN</code>.</li>
</ol></li>
<li><p>Last step, commit and push your <code>.looper.yml</code> to the repo, then let's goto <a href="./Build%20the%20looper%20job.md">Build the looper job</a>.</p></li>
</ol>
</div>
<div class="training-doc-nav-btn">
<a href="./Build the looper job"><img src="/images/training/btn-right.png" srcset="/images/training/btn-right%402x.png 2x, /images/training/btn-right%403x.png 3x" /></a>
</div>

  </div>
  <div class="clear"></div>
</div>
<script type="text/javascript">
  var elements = document.getElementsByTagName('pre');
  for (var i = 0; i < elements.length; i++) {
    elements[i].className += " line-numbers";
    if (!elements[i].children[0].className) {
      elements[i].children[0].className = "language-javascript";
    }
  }
</script>
<script type="text/javascript" src="/js/prism.js"></script>
	</div>

	<footer>
		<img class="left-footer-logo" alt="Left Footer Logo"
			 src="/documentation/images/dxt-logo.png"
			 srcset="/documentation/images/dxt-logo%402x.png 2x,
					 /documentation/images/dxt-logo%403x.png 3x">
		
		<span class="copyright">&copy; 2018 Walmart Inc.</span>
		
		<img class="right-footer-logo" alt="Right Footer Logo"
			 src="/documentation/images/walmartlabs-logo.png"
			 srcset="/documentation/images/walmartlabs-logo%402x.png 2x,
			 		 /documentation/images/walmartlabs-logo%403x.png 3x">
	</footer>

</body>
</html>
